version: '3'
services:
  tkinter:
    build:
      context: ${SRC}
    container_name: 'mylib'
    stdin_open: true
    working_dir: '/app'
    tty: true
    volumes:
      - ${SRC}:/app
    environment:
      - DISPLAY=${DISPLAY}
      - JSON_FILE=${JSON_FILE}
