version: '3'
services:
  python3:
    build: .
    container_name: 'mylib'
    stdin_open: true
    working_dir: '/app'
    tty: true
    volumes:
      - .:/app
    environment:
      environment:
      - JSON_FILE=${JSON_FILE}
      - DISPLAY=:0.0
